[package]
name = "ironchip"
version = "0.1.0"
edition = "2021"
authors = ["Marval13 <dbaro13@gmail.com>"]

[dependencies]
sdl2 = "0.35.2"
clap = { version = "3.1.2", features = ["derive"] }
chip8 = { path = "../chip8" }
